// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main_controllers

import (
	"itineraryplanner/controllers"
	"itineraryplanner/dal"
	"itineraryplanner/dal/db"
	"itineraryplanner/service"
)

// Injectors from wire.go:

func InitializeMainCreateAttractionController() (MainAttractionController, error) {
	mainMongoDB := db.GetMainMongoDatabase()
	attractionDal := dal.NewCreateAttractionDal(mainMongoDB)
	tagDal := dal.NewTagDal(mainMongoDB)
	attractionService := service.NewCreateAttractionService(attractionDal, tagDal)

	attractionController := controllers.NewCreateAttractionController(attractionService)
	mainCreateAttractionController := NewMainCreateAttractionController(attractionController)
	return mainCreateAttractionController, nil
}
